const items = {
  carousel: [
    {
      id: 1,
      title: "carousel_title_1",
      subtitle: "carousel_subtitle_1",
      url: "/img/hugo-sousa-BghGseQbAkA-unsplash.jpg",
      path: "/about",
    },
    {
      id: 2,
      title: "carousel_title_2",
      subtitle: "carousel_subtitle_2",
      url: "/img/pexels-vecislavas-popa-1571459.jpg",
      path: "",
    },
    {
      id: 3,
      title: "carousel_title_3",
      subtitle: "carousel_subtitle_3",
      url: "/img/dannie-jing-3GZlhROZIQg-unsplash.jpg",
      path: "",
    },
    {
      id: 4,
      title: "carousel_title_4",
      subtitle: "carousel_subtitle_4",
      url: "/img/pexels-karolina-grabowska-7283170.jpg",
      path: "",
    },
    {
      id: 5,
      title: "carousel_title_5",
      subtitle: "carousel_subtitle_5",
      url: "/img/144aa06e3533a4d74e21603b07cee465.jpg",
      path: "",
    },
    {
      id: 6,
      title: "carousel_title_6",
      subtitle: "carousel_subtitle_6",
      url: "/img/0110.jpg",
      path: "",
    },
    {
      id: 7,
      title: "carousel_title_7",
      subtitle: "carousel_subtitle_7",
      url: "/img/vfw33x2v0ocvywho3cof.jpg",
      path: "",
    },
  ],
  categories: [
    {
      id: 1,
      name: "residental",
      title: "category_title_1",
      subtitle: "category_subtitle_1",
      url: "/img/istockphoto-1159873271-612x612.jpg",
    },
    {
      id: 2,
      name: "interior",
      title: "category_title_2",
      subtitle: "category_subtitle_2",
      url: "/img/pexels-vecislavas-popa-1571459.jpg",
    },
    {
      id: 3,
      name: "building",
      title: "category_title_3",
      subtitle: "category_subtitle_3",
      url: "/img/vfw33x2v0ocvywho3cof.jpg",
    },
    {
      id: 4,
      name: "landscape",
      title: "category_title_4",
      subtitle: "category_subtitle_4",
      url: "/img/Arch2O-20-landscape-architecture-free-books-and-presentation-tutorials-15.jpg",
    },
    {
      id: 5,
      name: "renovation",
      title: "category_title_5",
      subtitle: "category_subtitle_5",
      url: "/img/istockphoto-1146295665-612x612.jpg",
    },
    {
      id: 6,
      name: "sculpture",
      title: "category_title_6",
      subtitle: "category_subtitle_6",
      url: "/img/f781f84a37411064e0421cd74c5781c4.jpg",
    },
    {
      id: 7,
      name: "painting",
      title: "category_title_7",
      subtitle: "category_subtitle_7",
      url: "/img/dannie-jing-3GZlhROZIQg-unsplash.jpg",
    },
    {
      id: 8,
      name: "lighting",
      title: "category_title_8",
      subtitle: "category_subtitle_8",
      url: "/img/20181204-R_G-033.jpg",
    },
    {
      id: 9,
      name: "fashion",
      title: "category_title_9",
      subtitle: "category_subtitle_9",
      url: "/img/pexels-karolina-grabowska-7283170.jpg",
    },
  ],
  projects: [
    {
      id: 1,
      category: ["residental"],
      title: "project_title_1",
      location: "project_location_1",
      desc: "project_desc_1",
      year: "project_year_1",
      images: [
        { url: "/img/projects/1/IMG_8484.JPG", title: "project 1 image" },
        { url: "/img/projects/1/IMG_8451.JPG", title: "project 1 image" },
        { url: "/img/projects/1/IMG_8468.JPG", title: "project 1 image" },
        { url: "/img/projects/1/IMG_8487.JPG", title: "project 1 image" },
      ],
    },
    {
      id: 2,
      category: ["residental", "interior"],
      title: "project_title_2",
      location: "project_location_2",
      desc: "project_desc_2",
      year: "project_year_2",
      images: [
        { url: "/img/projects/2/IMG_3024.jpg", title: "project 1 image" },
        { url: "/img/projects/2/IMG_3026.jpg", title: "project 1 image" },
        { url: "/img/projects/2/IMG_3028.jpg", title: "project 1 image" },
        { url: "/img/projects/2/IMG_3029.jpg", title: "project 1 image" },
        { url: "/img/projects/2/09 (2).jpg", title: "project 1 image" },
        { url: "/img/projects/2/09.jpg", title: "project 1 image" },
      ],
    },
    {
      id: 3,
      category: ["residental"],
      title: "project_title_3",
      location: "project_location_3",
      desc: "project_desc_3",
      year: "project_year_3",
      images: [
        { url: "/img/projects/3/IMG_2185.jpg", title: "project 3 image" },
        { url: "/img/projects/3/IMG_2200.jpg", title: "project 3 image" },
        { url: "/img/projects/3/IMG_2202.jpg", title: "project 3 image" },
        { url: "/img/projects/3/IMG_2206.jpg", title: "project 3 image" },
        { url: "/img/projects/3/IMG_2212.jpg", title: "project 3 image" },
      ],
    },
    {
      id: 4,
      category: ["residental"],
      title: "project_title_4",
      location: "project_location_4",
      desc: "project_desc_4",
      year: "project_year_4",
      images: [
        { url: "/img/projects/4/IMG_1879.jpg", title: "project 4 img" },
        { url: "/img/projects/4/IMG_1804.jpg", title: "project 4 img" },
        { url: "/img/projects/4/IMG_1816.jpg", title: "project 4 img" },
        { url: "/img/projects/4/IMG_1835.jpg", title: "project 4 img" },
      ],
    },
    {
      id: 5,
      category: ["residental"],
      title: "project_title_5",
      location: "project_location_5",
      desc: "project_desc_5",
      year: "project_year_5",
      images: [
        { url: "/img/projects/5/02!.jpg", title: "project 5 image" },
        { url: "/img/projects/5/08.jpg", title: "project 5 image" },
        { url: "/img/projects/5/09 (2).jpg", title: "project 5 image" },
        { url: "/img/projects/5/09.jpg", title: "project 5 image" },
      ],
    },
    {
      id: 6,
      category: ["sculpture"],
      title: "project_title_6",
      location: "project_location_6",
      desc: "project_desc_6",
      year: "project_year_6",
      images: [
        { url: "/img/projects/6/012.jpg", title: "project 6 image" },
        { url: "/img/projects/6/013.jpg", title: "project 6 image" },
      ],
    },
    {
      id: 7,
      category: ["sculpture"],
      title: "project_title_7",
      location: "project_location_7",
      desc: "project_desc_7",
      year: "project_year_7",
      images: [
        { url: "/img/projects/7/014.jpg", title: "project 7 image" },
        { url: "/img/projects/7/015.jpg", title: "project 7 image" },
        { url: "/img/projects/7/016.jpg", title: "project 7 image" },
        { url: "/img/projects/7/017.jpg", title: "project 7 image" },
      ],
    },
    {
      id: 8,
      category: ["sculpture"],
      title: "project_title_8",
      location: "project_location_8",
      desc: "project_desc_8",
      year: "project_year_8",
      images: [
        { url: "/img/projects/8/018.jpg", title: "project 8 image" },
        { url: "/img/projects/8/019.jpg", title: "project 8 image" },
        { url: "/img/projects/8/0110.jpg", title: "project 8 image" },
        { url: "/img/projects/8/0111.jpg", title: "project 8 image" },
      ],
    },
    {
      id: 9,
      category: ["sculpture"],
      title: "project_title_9",
      location: "project_location_9",
      desc: "project_desc_9",
      year: "project_year_9",
      images: [
        { url: "/img/projects/9/London02.jpg", title: "project 9 image" },
      ],
    },
    {
      id: 10,
      category: ["sculpture"],
      title: "project_title_10",
      location: "project_location_10",
      desc: "project_desc_10",
      year: "project_year_10",
      images: [
        { url: "/img/projects/10/IMG_2636.jpg", title: "project 10 image" },
        { url: "/img/projects/10/IMG_2871 01.jpg", title: "project 10 image" },
        { url: "/img/projects/10/IMG_2871.jpg", title: "project 10 image" },
        { url: "/img/projects/10/IMG_7081.jpg", title: "project 10 image" },
      ],
    },
    {
      id: 11,
      category: ["residental", "building"],
      title: "project_title_11",
      location: "project_location_11",
      desc: "project_desc_11",
      year: "project_year_11",
      images: [
        { url: "/img/projects/11/image 2.jpg", title: "project 11 image" },
        { url: "/img/projects/11/image 3.jpg", title: "project 11 image" },
        { url: "/img/projects/11/image.jpg", title: "project 11 image" },
        { url: "/img/projects/11/IMG_0276.jpg", title: "project 11 image" },
        { url: "/img/projects/11/IMG_0597.jpg", title: "project 11 image" },
        { url: "/img/projects/11/IMG_0604.jpg", title: "project 11 image" },
        { url: "/img/projects/11/IMG_9305.jpg", title: "project 11 image" },
      ],
    },
    {
      id: 12,
      category: ["residental", "building"],
      title: "project_title_12",
      location: "project_location_12",
      desc: "project_desc_12",
      year: "project_year_12",
      images: [
        { url: "/img/projects/12/image2.jpg", title: "project 12 image" },
        { url: "/img/projects/12/IMG_0277.jpg", title: "project 12 image" },
        { url: "/img/projects/12/IMG_5290.jpg", title: "project 12 image" },
        { url: "/img/projects/12/IMG_7705.jpg", title: "project 12 image" },
        { url: "/img/projects/12/IMG_7706.jpg", title: "project 12 image" },
      ],
    },
  ],
};

export default items;
